In [34]:
import pandas as pd

In [35]:
cust_info=pd.read_csv('customer_info.csv')
cust_info=cust_info.set_index('customer_id')
cust_info.head(10)

,customer_name,customer_gender,customer_birthdate,kids_home,teens_home,number_complaints,distinct_stores_visited,lifetime_spend_groceries,lifetime_spend_electronics,typical_hour,...,lifetime_spend_fish,lifetime_spend_hygiene,lifetime_spend_videogames,lifetime_spend_petfood,lifetime_total_distinct_products,percentage_of_products_bought_promotion,year_first_transaction,loyalty_card_number,latitude,longitude
customer_id,,,,,,,,,,,,,,,,,,,,,
3,Bsc. Crystal Kitchens,female,02/12/1970 01:36 PM,1.0,1.0,1.0,3.0,11731.0,4553.0,NaN,...,213.0,552.0,256.0,384.0,189.0,0.631599,2020.0,1.0,38.794428,-9.215739
4,Bsc. Glenda Bauman,female,11/13/1975 06:58 PM,1.0,0.0,0.0,2.0,13694.0,963.0,NaN,...,15.0,1880.0,333.0,665.0,130.0,0.149890,2013.0,1.0,38.751711,-9.179611
5,Msc. Antonio Campbell,male,09/10/1971 10:07 AM,0.0,0.0,NaN,2.0,12407.0,0.0,11.0,...,273.0,507.0,101.0,222.0,81.0,0.069126,2005.0,NaN,38.780678,-9.160656
7,John Kelling,male,10/23/1982 11:20 AM,0.0,0.0,2.0,1.0,7493.0,1105.0,18.0,...,1083.0,485.0,1656.0,184.0,92.0,0.253609,2021.0,1.0,38.739548,-9.148679
8,Arthur Dematteo,male,08/04/1969 10:22 PM,0.0,0.0,3.0,1.0,9187.0,10841.0,17.0,...,1015.0,297.0,1258.0,441.0,6.0,0.186569,2021.0,1.0,38.733071,-9.188188
9,Msc. Nadine Garcia,female,10/09/1968 04:01 AM,1.0,1.0,1.0,6.0,16530.0,1156.0,6.0,...,76.0,513.0,225.0,NaN,84.0,0.150646,2011.0,1.0,38.735577,-9.172423
10,Phd. Franklin Alba,male,06/09/1971 05:08 AM,2.0,1.0,0.0,1.0,22240.0,NaN,9.0,...,1723.0,886.0,203.0,119.0,202.0,0.275412,2014.0,1.0,38.730322,-9.144022
11,Bsc. Robert Hansing,male,07/19/1977 10:22 AM,1.0,1.0,1.0,6.0,29765.0,1543.0,10.0,...,731.0,1240.0,1849.0,397.0,180.0,0.164251,2017.0,1.0,38.739328,-9.225047
12,Phd. Dorothy Pacheco,female,05/19/2000 03:02 AM,0.0,0.0,0.0,2.0,9281.0,254.0,18.0,...,598.0,673.0,71.0,64.0,29.0,-0.131176,2018.0,NaN,38.748616,-9.167756
14,Msc. Arron Burgener,male,11/28/1948 07:53 PM,1.0,0.0,1.0,3.0,7981.0,2151.0,12.0,...,24.0,1393.0,178.0,90.0,57.0,0.197353,2017.0,1.0,38.788819,-9.184158

In [36]:
cust_info.info()

<class 'pandas.core.frame.DataFrame'>
Index: 33038 entries, 3 to 40000
Data columns (total 24 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   customer_name                            33038 non-null  object
 1   customer_gender                          33038 non-null  object
 2   customer_birthdate                       32873 non-null  object
 3   kids_home                                32708 non-null  float64
 4   teens_home                               32708 non-null  float64
 5   number_complaints                        32377 non-null  float64
 6   distinct_stores_visited                  32708 non-null  float64
 7   lifetime_spend_groceries                 33038 non-null  float64
 8   lifetime_spend_electronics               32377 non-null  float64
 9   typical_hour                             32377 non-null  float64
 10  lifetime_spend_vegetables                32377 non-null  float64
 11  lifetime_spend_nonalcohol_drinks         33038 non-null  float64
 12  lifetime_spend_alcohol_drinks            32708 non-null  float64
 13  lifetime_spend_meat                      32377 non-null  float64
 14  lifetime_spend_fish                      32047 non-null  float64
 15  lifetime_spend_hygiene                   32708 non-null  float64
 16  lifetime_spend_videogames                32377 non-null  float64
 17  lifetime_spend_petfood                   32377 non-null  float64
 18  lifetime_total_distinct_products         33038 non-null  float64
 19  percentage_of_products_bought_promotion  32708 non-null  float64
 20  year_first_transaction                   33038 non-null  float64
 21  loyalty_card_number                      19932 non-null  float64
 22  latitude                                 33038 non-null  float64
 23  longitude                                33038 non-null  float64
dtypes: float64(21), object(3)
memory usage: 6.3+ MB

In [37]:
cust_info.describe()

,kids_home,teens_home,number_complaints,distinct_stores_visited,lifetime_spend_groceries,lifetime_spend_electronics,typical_hour,lifetime_spend_vegetables,lifetime_spend_nonalcohol_drinks,lifetime_spend_alcohol_drinks,...,lifetime_spend_fish,lifetime_spend_hygiene,lifetime_spend_videogames,lifetime_spend_petfood,lifetime_total_distinct_products,percentage_of_products_bought_promotion,year_first_transaction,loyalty_card_number,latitude,longitude
count,32708.000000,32708.000000,32377.000000,32708.000000,33038.000000,32377.000000,32377.000000,32377.000000,33038.000000,32708.000000,...,32047.000000,32708.00000,32377.000000,32377.000000,33038.000000,32708.000000,33038.000000,19932.0,33038.000000,33038.000000
mean,1.116118,0.898893,0.930846,3.167941,16306.227798,2763.080088,12.659388,727.223801,464.352776,622.144185,...,608.781228,820.34646,373.900917,336.217099,148.914644,0.318866,2015.311853,1.0,38.749694,-9.154549
std,1.150186,0.962924,0.894658,1.674114,11985.903518,3453.191495,4.854708,654.633087,275.767976,517.744320,...,497.068874,608.31732,460.782042,160.234980,105.922907,0.283638,5.032196,0.0,0.022498,0.028581
min,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,6.000000,0.000000,0.000000,0.000000,...,0.000000,0.00000,0.000000,0.000000,0.000000,-1.274940,1993.000000,1.0,38.687987,-9.232989
25%,0.000000,0.000000,0.000000,2.000000,8647.000000,579.000000,8.000000,224.000000,241.000000,201.000000,...,171.000000,362.00000,125.000000,225.000000,67.000000,0.122359,2012.000000,1.0,38.734079,-9.173732
50%,1.000000,1.000000,1.000000,3.000000,13002.500000,1470.000000,12.000000,471.000000,421.000000,483.000000,...,511.000000,686.00000,223.000000,327.000000,123.000000,0.239449,2015.000000,1.0,38.748286,-9.156689
75%,1.000000,1.000000,1.000000,4.000000,20807.000000,3745.000000,16.000000,1074.000000,640.000000,891.250000,...,923.000000,1120.00000,374.000000,435.000000,210.000000,0.469390,2019.000000,1.0,38.765779,-9.139608
max,8.000000,6.000000,7.000000,10.000000,104670.000000,35299.000000,23.000000,3337.000000,2180.000000,3704.000000,...,3172.000000,3482.00000,3936.000000,1224.000000,600.000000,1.000000,2029.000000,1.0,38.823693,-9.035697

In [38]:
cust_info.isna().sum()

customer_name                                  0
customer_gender                                0
customer_birthdate                           165
kids_home                                    330
teens_home                                   330
number_complaints                            661
distinct_stores_visited                      330
lifetime_spend_groceries                       0
lifetime_spend_electronics                   661
typical_hour                                 661
lifetime_spend_vegetables                    661
lifetime_spend_nonalcohol_drinks               0
lifetime_spend_alcohol_drinks                330
lifetime_spend_meat                          661
lifetime_spend_fish                          991
lifetime_spend_hygiene                       330
lifetime_spend_videogames                    661
lifetime_spend_petfood                       661
lifetime_total_distinct_products               0
percentage_of_products_bought_promotion      330
year_first_transaction                         0
loyalty_card_number                        13106
latitude                                       0
longitude                                      0
dtype: int64

In [39]:
cust_info.duplicated().sum()

np.int64(0)

In [49]:
cust_info['education_level'] = cust_info['customer_name'].str.extract(r'^(Bsc|Msc|Phd)\.').fillna('None')
cust_info.head(10)

,customer_name,customer_gender,customer_birthdate,kids_home,teens_home,number_complaints,distinct_stores_visited,lifetime_spend_groceries,lifetime_spend_electronics,typical_hour,...,lifetime_spend_videogames,lifetime_spend_petfood,lifetime_total_distinct_products,percentage_of_products_bought_promotion,year_first_transaction,loyalty_card_number,latitude,longitude,education,education_level
customer_id,,,,,,,,,,,,,,,,,,,,,
3,Bsc. Crystal Kitchens,female,02/12/1970 01:36 PM,1.0,1.0,1.0,3.0,11731.0,4553.0,NaN,...,256.0,384.0,189.0,0.631599,2020.0,1.0,38.794428,-9.215739,Bsc.,Bsc
4,Bsc. Glenda Bauman,female,11/13/1975 06:58 PM,1.0,0.0,0.0,2.0,13694.0,963.0,NaN,...,333.0,665.0,130.0,0.149890,2013.0,1.0,38.751711,-9.179611,Bsc.,Bsc
5,Msc. Antonio Campbell,male,09/10/1971 10:07 AM,0.0,0.0,NaN,2.0,12407.0,0.0,11.0,...,101.0,222.0,81.0,0.069126,2005.0,NaN,38.780678,-9.160656,Msc.,Msc
7,John Kelling,male,10/23/1982 11:20 AM,0.0,0.0,2.0,1.0,7493.0,1105.0,18.0,...,1656.0,184.0,92.0,0.253609,2021.0,1.0,38.739548,-9.148679,NaN,None
8,Arthur Dematteo,male,08/04/1969 10:22 PM,0.0,0.0,3.0,1.0,9187.0,10841.0,17.0,...,1258.0,441.0,6.0,0.186569,2021.0,1.0,38.733071,-9.188188,NaN,None
9,Msc. Nadine Garcia,female,10/09/1968 04:01 AM,1.0,1.0,1.0,6.0,16530.0,1156.0,6.0,...,225.0,NaN,84.0,0.150646,2011.0,1.0,38.735577,-9.172423,Msc.,Msc
10,Phd. Franklin Alba,male,06/09/1971 05:08 AM,2.0,1.0,0.0,1.0,22240.0,NaN,9.0,...,203.0,119.0,202.0,0.275412,2014.0,1.0,38.730322,-9.144022,Phd.,Phd
11,Bsc. Robert Hansing,male,07/19/1977 10:22 AM,1.0,1.0,1.0,6.0,29765.0,1543.0,10.0,...,1849.0,397.0,180.0,0.164251,2017.0,1.0,38.739328,-9.225047,Bsc.,Bsc
12,Phd. Dorothy Pacheco,female,05/19/2000 03:02 AM,0.0,0.0,0.0,2.0,9281.0,254.0,18.0,...,71.0,64.0,29.0,-0.131176,2018.0,NaN,38.748616,-9.167756,Phd.,Phd
14,Msc. Arron Burgener,male,11/28/1948 07:53 PM,1.0,0.0,1.0,3.0,7981.0,2151.0,12.0,...,178.0,90.0,57.0,0.197353,2017.0,1.0,38.788819,-9.184158,Msc.,Msc

In [54]:
cust_info['customer_birthdate'] = pd.to_datetime(cust_info['customer_birthdate'], format='%m/%d/%Y %I:%M %p')
reference_date = pd.Timestamp('2024-01-01')
cust_info['age'] = (reference_date - cust_info['customer_birthdate']).dt.days // 365
print(cust_info['age'].describe())
print(f"Missing ages: {cust_info['age'].isna().sum()}")  # should be 165

count    32873.000000
mean        52.154047
std         18.077126
min         22.000000
25%         36.000000
50%         52.000000
75%         68.000000
max         84.000000
Name: age, dtype: float64
Missing ages: 165

In [55]:
cust_info = cust_info.drop(columns=['customer_birthdate'])
cust_info.head(10)

,customer_name,customer_gender,kids_home,teens_home,number_complaints,distinct_stores_visited,lifetime_spend_groceries,lifetime_spend_electronics,typical_hour,lifetime_spend_vegetables,...,lifetime_spend_petfood,lifetime_total_distinct_products,percentage_of_products_bought_promotion,year_first_transaction,loyalty_card_number,latitude,longitude,education,education_level,age
customer_id,,,,,,,,,,,,,,,,,,,,,
3,Bsc. Crystal Kitchens,female,1.0,1.0,1.0,3.0,11731.0,4553.0,NaN,373.0,...,384.0,189.0,0.631599,2020.0,1.0,38.794428,-9.215739,Bsc.,Bsc,53.0
4,Bsc. Glenda Bauman,female,1.0,0.0,0.0,2.0,13694.0,963.0,NaN,2012.0,...,665.0,130.0,0.149890,2013.0,1.0,38.751711,-9.179611,Bsc.,Bsc,48.0
5,Msc. Antonio Campbell,male,0.0,0.0,NaN,2.0,12407.0,0.0,11.0,555.0,...,222.0,81.0,0.069126,2005.0,NaN,38.780678,-9.160656,Msc.,Msc,52.0
7,John Kelling,male,0.0,0.0,2.0,1.0,7493.0,1105.0,18.0,84.0,...,184.0,92.0,0.253609,2021.0,1.0,38.739548,-9.148679,NaN,None,41.0
8,Arthur Dematteo,male,0.0,0.0,3.0,1.0,9187.0,10841.0,17.0,380.0,...,441.0,6.0,0.186569,2021.0,1.0,38.733071,-9.188188,NaN,None,54.0
9,Msc. Nadine Garcia,female,1.0,1.0,1.0,6.0,16530.0,1156.0,6.0,1708.0,...,NaN,84.0,0.150646,2011.0,1.0,38.735577,-9.172423,Msc.,Msc,55.0
10,Phd. Franklin Alba,male,2.0,1.0,0.0,1.0,22240.0,NaN,9.0,1284.0,...,119.0,202.0,0.275412,2014.0,1.0,38.730322,-9.144022,Phd.,Phd,52.0
11,Bsc. Robert Hansing,male,1.0,1.0,1.0,6.0,29765.0,1543.0,10.0,190.0,...,397.0,180.0,0.164251,2017.0,1.0,38.739328,-9.225047,Bsc.,Bsc,46.0
12,Phd. Dorothy Pacheco,female,0.0,0.0,0.0,2.0,9281.0,254.0,18.0,125.0,...,64.0,29.0,-0.131176,2018.0,NaN,38.748616,-9.167756,Phd.,Phd,23.0
14,Msc. Arron Burgener,male,1.0,0.0,1.0,3.0,7981.0,2151.0,12.0,1659.0,...,90.0,57.0,0.197353,2017.0,1.0,38.788819,-9.184158,Msc.,Msc,75.0

In [56]:
cust_info['has_loyalty_card'] = cust_info['loyalty_card_number'].notna().astype(int)
print(cust_info['has_loyalty_card'].value_counts())

has_loyalty_card
1    19932
0    13106
Name: count, dtype: int64

In [57]:
cust_info = cust_info.drop(columns=['loyalty_card_number'])
cust_info.head(10)

,customer_name,customer_gender,kids_home,teens_home,number_complaints,distinct_stores_visited,lifetime_spend_groceries,lifetime_spend_electronics,typical_hour,lifetime_spend_vegetables,...,lifetime_spend_petfood,lifetime_total_distinct_products,percentage_of_products_bought_promotion,year_first_transaction,latitude,longitude,education,education_level,age,has_loyalty_card
customer_id,,,,,,,,,,,,,,,,,,,,,
3,Bsc. Crystal Kitchens,female,1.0,1.0,1.0,3.0,11731.0,4553.0,NaN,373.0,...,384.0,189.0,0.631599,2020.0,38.794428,-9.215739,Bsc.,Bsc,53.0,1
4,Bsc. Glenda Bauman,female,1.0,0.0,0.0,2.0,13694.0,963.0,NaN,2012.0,...,665.0,130.0,0.149890,2013.0,38.751711,-9.179611,Bsc.,Bsc,48.0,1
5,Msc. Antonio Campbell,male,0.0,0.0,NaN,2.0,12407.0,0.0,11.0,555.0,...,222.0,81.0,0.069126,2005.0,38.780678,-9.160656,Msc.,Msc,52.0,0
7,John Kelling,male,0.0,0.0,2.0,1.0,7493.0,1105.0,18.0,84.0,...,184.0,92.0,0.253609,2021.0,38.739548,-9.148679,NaN,None,41.0,1
8,Arthur Dematteo,male,0.0,0.0,3.0,1.0,9187.0,10841.0,17.0,380.0,...,441.0,6.0,0.186569,2021.0,38.733071,-9.188188,NaN,None,54.0,1
9,Msc. Nadine Garcia,female,1.0,1.0,1.0,6.0,16530.0,1156.0,6.0,1708.0,...,NaN,84.0,0.150646,2011.0,38.735577,-9.172423,Msc.,Msc,55.0,1
10,Phd. Franklin Alba,male,2.0,1.0,0.0,1.0,22240.0,NaN,9.0,1284.0,...,119.0,202.0,0.275412,2014.0,38.730322,-9.144022,Phd.,Phd,52.0,1
11,Bsc. Robert Hansing,male,1.0,1.0,1.0,6.0,29765.0,1543.0,10.0,190.0,...,397.0,180.0,0.164251,2017.0,38.739328,-9.225047,Bsc.,Bsc,46.0,1
12,Phd. Dorothy Pacheco,female,0.0,0.0,0.0,2.0,9281.0,254.0,18.0,125.0,...,64.0,29.0,-0.131176,2018.0,38.748616,-9.167756,Phd.,Phd,23.0,0
14,Msc. Arron Burgener,male,1.0,0.0,1.0,3.0,7981.0,2151.0,12.0,1659.0,...,90.0,57.0,0.197353,2017.0,38.788819,-9.184158,Msc.,Msc,75.0,1