In [1]:
import pandas as pd

In [37]:
cust_info=pd.read_csv('customer_info.csv')
cust_info=cust_info.drop(columns=['customer_id'])
cust_info.head(10)

,customer_name,customer_gender,customer_birthdate,kids_home,teens_home,number_complaints,distinct_stores_visited,lifetime_spend_groceries,lifetime_spend_electronics,typical_hour,...,lifetime_spend_fish,lifetime_spend_hygiene,lifetime_spend_videogames,lifetime_spend_petfood,lifetime_total_distinct_products,percentage_of_products_bought_promotion,year_first_transaction,loyalty_card_number,latitude,longitude
0,Bsc. Crystal Kitchens,female,02/12/1970 01:36 PM,1.0,1.0,1.0,3.0,11731.0,4553.0,NaN,...,213.0,552.0,256.0,384.0,189.0,0.631599,2020.0,1.0,38.794428,-9.215739
1,Bsc. Glenda Bauman,female,11/13/1975 06:58 PM,1.0,0.0,0.0,2.0,13694.0,963.0,NaN,...,15.0,1880.0,333.0,665.0,130.0,0.149890,2013.0,1.0,38.751711,-9.179611
2,Msc. Antonio Campbell,male,09/10/1971 10:07 AM,0.0,0.0,NaN,2.0,12407.0,0.0,11.0,...,273.0,507.0,101.0,222.0,81.0,0.069126,2005.0,NaN,38.780678,-9.160656
3,John Kelling,male,10/23/1982 11:20 AM,0.0,0.0,2.0,1.0,7493.0,1105.0,18.0,...,1083.0,485.0,1656.0,184.0,92.0,0.253609,2021.0,1.0,38.739548,-9.148679
4,Arthur Dematteo,male,08/04/1969 10:22 PM,0.0,0.0,3.0,1.0,9187.0,10841.0,17.0,...,1015.0,297.0,1258.0,441.0,6.0,0.186569,2021.0,1.0,38.733071,-9.188188
5,Msc. Nadine Garcia,female,10/09/1968 04:01 AM,1.0,1.0,1.0,6.0,16530.0,1156.0,6.0,...,76.0,513.0,225.0,NaN,84.0,0.150646,2011.0,1.0,38.735577,-9.172423
6,Phd. Franklin Alba,male,06/09/1971 05:08 AM,2.0,1.0,0.0,1.0,22240.0,NaN,9.0,...,1723.0,886.0,203.0,119.0,202.0,0.275412,2014.0,1.0,38.730322,-9.144022
7,Bsc. Robert Hansing,male,07/19/1977 10:22 AM,1.0,1.0,1.0,6.0,29765.0,1543.0,10.0,...,731.0,1240.0,1849.0,397.0,180.0,0.164251,2017.0,1.0,38.739328,-9.225047
8,Phd. Dorothy Pacheco,female,05/19/2000 03:02 AM,0.0,0.0,0.0,2.0,9281.0,254.0,18.0,...,598.0,673.0,71.0,64.0,29.0,-0.131176,2018.0,NaN,38.748616,-9.167756
9,Msc. Arron Burgener,male,11/28/1948 07:53 PM,1.0,0.0,1.0,3.0,7981.0,2151.0,12.0,...,24.0,1393.0,178.0,90.0,57.0,0.197353,2017.0,1.0,38.788819,-9.184158

In [38]:
cust_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33038 entries, 0 to 33037
Data columns (total 24 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   customer_name                            33038 non-null  object
 1   customer_gender                          33038 non-null  object
 2   customer_birthdate                       32873 non-null  object
 3   kids_home                                32708 non-null  float64
 4   teens_home                               32708 non-null  float64
 5   number_complaints                        32377 non-null  float64
 6   distinct_stores_visited                  32708 non-null  float64
 7   lifetime_spend_groceries                 33038 non-null  float64
 8   lifetime_spend_electronics               32377 non-null  float64
 9   typical_hour                             32377 non-null  float64
 10  lifetime_spend_vegetables                32377 non-null  float64
 11  lifetime_spend_nonalcohol_drinks         33038 non-null  float64
 12  lifetime_spend_alcohol_drinks            32708 non-null  float64
 13  lifetime_spend_meat                      32377 non-null  float64
 14  lifetime_spend_fish                      32047 non-null  float64
 15  lifetime_spend_hygiene                   32708 non-null  float64
 16  lifetime_spend_videogames                32377 non-null  float64
 17  lifetime_spend_petfood                   32377 non-null  float64
 18  lifetime_total_distinct_products         33038 non-null  float64
 19  percentage_of_products_bought_promotion  32708 non-null  float64
 20  year_first_transaction                   33038 non-null  float64
 21  loyalty_card_number                      19932 non-null  float64
 22  latitude                                 33038 non-null  float64
 23  longitude                                33038 non-null  float64
dtypes: float64(21), object(3)
memory usage: 6.0+ MB

In [39]:
# 1. Your clean list of degrees
degrees = ['Bsc.', 'Msc.', 'Phd.']

# 2. Make sure the names are stripped of hidden spaces
cust_info['customer_name'] = cust_info['customer_name'].str.strip()

# 3. Create the regex pattern
pattern = r'^(' + '|'.join(degrees) + ')'

# 4. CRITICAL STEP: Use .str.extract() so pandas pulls out the matching text
cust_info['education'] = cust_info['customer_name'].str.extract(pattern)
cust_info.head(10)

,customer_name,customer_gender,customer_birthdate,kids_home,teens_home,number_complaints,distinct_stores_visited,lifetime_spend_groceries,lifetime_spend_electronics,typical_hour,...,lifetime_spend_hygiene,lifetime_spend_videogames,lifetime_spend_petfood,lifetime_total_distinct_products,percentage_of_products_bought_promotion,year_first_transaction,loyalty_card_number,latitude,longitude,education
0,Bsc. Crystal Kitchens,female,02/12/1970 01:36 PM,1.0,1.0,1.0,3.0,11731.0,4553.0,NaN,...,552.0,256.0,384.0,189.0,0.631599,2020.0,1.0,38.794428,-9.215739,Bsc.
1,Bsc. Glenda Bauman,female,11/13/1975 06:58 PM,1.0,0.0,0.0,2.0,13694.0,963.0,NaN,...,1880.0,333.0,665.0,130.0,0.149890,2013.0,1.0,38.751711,-9.179611,Bsc.
2,Msc. Antonio Campbell,male,09/10/1971 10:07 AM,0.0,0.0,NaN,2.0,12407.0,0.0,11.0,...,507.0,101.0,222.0,81.0,0.069126,2005.0,NaN,38.780678,-9.160656,Msc.
3,John Kelling,male,10/23/1982 11:20 AM,0.0,0.0,2.0,1.0,7493.0,1105.0,18.0,...,485.0,1656.0,184.0,92.0,0.253609,2021.0,1.0,38.739548,-9.148679,NaN
4,Arthur Dematteo,male,08/04/1969 10:22 PM,0.0,0.0,3.0,1.0,9187.0,10841.0,17.0,...,297.0,1258.0,441.0,6.0,0.186569,2021.0,1.0,38.733071,-9.188188,NaN
5,Msc. Nadine Garcia,female,10/09/1968 04:01 AM,1.0,1.0,1.0,6.0,16530.0,1156.0,6.0,...,513.0,225.0,NaN,84.0,0.150646,2011.0,1.0,38.735577,-9.172423,Msc.
6,Phd. Franklin Alba,male,06/09/1971 05:08 AM,2.0,1.0,0.0,1.0,22240.0,NaN,9.0,...,886.0,203.0,119.0,202.0,0.275412,2014.0,1.0,38.730322,-9.144022,Phd.
7,Bsc. Robert Hansing,male,07/19/1977 10:22 AM,1.0,1.0,1.0,6.0,29765.0,1543.0,10.0,...,1240.0,1849.0,397.0,180.0,0.164251,2017.0,1.0,38.739328,-9.225047,Bsc.
8,Phd. Dorothy Pacheco,female,05/19/2000 03:02 AM,0.0,0.0,0.0,2.0,9281.0,254.0,18.0,...,673.0,71.0,64.0,29.0,-0.131176,2018.0,NaN,38.748616,-9.167756,Phd.
9,Msc. Arron Burgener,male,11/28/1948 07:53 PM,1.0,0.0,1.0,3.0,7981.0,2151.0,12.0,...,1393.0,178.0,90.0,57.0,0.197353,2017.0,1.0,38.788819,-9.184158,Msc.